name: gto_trainer_master
description: 一款德州扑克GTO（游戏理论最优）策略训练应用，帮助玩家在真实对局中实现最优决策。
# publish_to: 'none' # 如果不发布到 pub.dev，请取消此行的注释

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

# 依赖项：您的应用需要这些包才能工作。
dependencies:
  flutter:
    sdk: flutter

  # 以下包用于iOS风格的图标。
  cupertino_icons: ^1.0.2

# 开发依赖项：这些包仅在开发和测试期间需要。
dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0

# 以下部分是Flutter特定的配置。
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # 要添加资源（如图片），请添加一个 assets 部分，像这样：
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # 要添加自定义字体，请添加一个 fonts 部分，像这样：
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
